name: settings
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.5 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/settings/assets/images/group.svg
    - packages/settings/assets/images/evaarrowbackfill.svg
    - packages/settings/assets/images/mdiaccount.svg
    - packages/settings/assets/images/evaedit2outline.svg
    - packages/settings/assets/images/ionnotifications.svg
    - packages/settings/assets/images/path.svg
    - packages/settings/assets/images/emptybar.svg
    - packages/settings/assets/images/rectangle23.svg
    - packages/settings/assets/images/rectangle21stroke.svg
    - packages/settings/assets/images/941.svg
